# Generated by Django 4.0.7 on 2022-08-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_type', models.CharField(choices=[('Bank', 'Bank'), ('ATM', 'ATM'), ('CSC', 'CSC'), ('PO', 'Post Office'), ('Bank_Mitra', 'Bank Mitra')], max_length=20)),
                ('financial_point_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=100)),
                ('unique_id_type', models.CharField(choices=[('IFSC', 'IFSC'), ('CSC_Id', 'CSC Id'), ('PIN_Code', 'PIN Code')], max_length=20)),
                ('unique_id', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Financial Points',
                'ordering': ['-id'],
            },
        ),
    ]
