# Generated by Django 3.2.14 on 2022-08-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_point', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialPointHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=10)),
                ('statedescr', models.CharField(max_length=200)),
                ('holiday', models.CharField(max_length=200)),
                ('holiday_reason', models.CharField(max_length=200)),
            ],
        ),
    ]
