# Generated by Django 3.2.14 on 2022-08-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_suggestions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingsuggestions',
            name='latitude',
            field=models.DecimalField(decimal_places=14, max_digits=20),
        ),
        migrations.AlterField(
            model_name='missingsuggestions',
            name='longitude',
            field=models.DecimalField(decimal_places=14, max_digits=20),
        ),
    ]
