# Generated by Django 4.0.7 on 2022-08-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10, verbose_name='Phone Number')),
                ('message', models.TextField(blank=True)),
                ('topic', models.CharField(choices=[('content_issue', 'Content Issue'), ('design_issue', 'Design Issue'), ('server_issue', 'Server Issue'), ('bug', 'Bug')], max_length=20)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
