# Generated by Django 4.0.7 on 2022-08-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developerfeedback',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
