# Generated by Django 4.0.7 on 2022-08-12 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jan_dhan_darshak.feedback.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialPointFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_type', models.CharField(choices=[('Bank', 'Bank'), ('ATM', 'ATM'), ('CSC', 'CSC'), ('PO', 'Post Office'), ('Bank_Mitra', 'Bank Mitra')], max_length=20)),
                ('financial_point_name', models.CharField(max_length=200)),
                ('unique_id_type', models.CharField(choices=[('IFSC', 'IFSC'), ('CSC_Id', 'CSC Id'), ('PIN_Code', 'PIN Code')], max_length=20)),
                ('unique_id', models.CharField(max_length=100, unique=True)),
                ('message', models.TextField(blank=True)),
                ('audio_message', models.FileField(blank=True, upload_to=jan_dhan_darshak.feedback.models.user_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
