# Generated by Django 4.0.7 on 2022-08-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_financialpointfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialpointfeedback',
            name='unique_id',
            field=models.CharField(max_length=100),
        ),
    ]
