# Generated by Django 4.0.7 on 2022-08-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=123245, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
